name: Deploy tutorial

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docs:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: tutorial
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build Sphinx site
      run: sphinx-build -b html ./ _build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        aws-access-key-id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload
      uses: datadesk/delivery-deploy-action@v1
      with:
        bucket: palewire-docs
        base-path: first-visual-story
        dir: tutorial/_build/
        should-cache: false
        use-accelerate-endpoint: false
        public: true