name: Deploy tutorial

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r tutorial/requirements.txt

    - name: Build Sphinx site
      run: cd tutorial && sphinx-build -b html ./ _build

    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
        source_dir: tutorial/_build/html/
        destination_dir: first-visual-story