name: Deploy tutorial

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r tutorial/requirements.txt

    - name: Build Sphinx site
      run: cd tutorial && sphinx-build -b html ./ _build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Upload
      uses: datadesk/delivery-deploy-action@v1
      with:
        bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
        base-path: first-visual-story
        dir: tutorial/_build/
        should-cache: true
        use-accelerate-endpoint: true
        public: true