name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tutorial:
    name: Tutorial
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r tutorial/requirements.txt

    - name: Build Sphinx site
      run: cd tutorial && sphinx-build -b html ./ _build

    - uses: actions/upload-artifact@v3
      with:
        name: tutorial
        path: tutorial/_build/

  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci --production

      - name: Build distribution
        run: npm run build
        env:
          BAKER_PATH_PREFIX: ${{ steps.get-slug.outputs.result }}

      - uses: actions/upload-artifact@v3
        with:
          name: demo
          path: _dist