name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tutorial:
    name: Tutorial
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: tutorial
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

      - id: install-pipenv
        name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        shell: bash

      - id: install-python-dependencies
        name: Install Python dependencies
        run: pipenv sync --dev
        shell: bash

    - name: Build Sphinx site
      run: pipenv run sphinx-build -b html ./ _build

    - uses: actions/upload-artifact@v4
      with:
        name: tutorial
        path: tutorial/_build/

  demo:
    name: Demo
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: demo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci --production

      - name: Build distribution
        run: npm run build
        env:
          BAKER_PATH_PREFIX: ${{ steps.get-slug.outputs.result }}

      - uses: actions/upload-artifact@v3
        with:
          name: demo
          path: demo/_dist