name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    - name: Upload release candidate
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: ./docs/

  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: install-node
        name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - id: install-npm
        name: Use npm v7
        run: npm install --global npm@7

      - id: install-project-modules
        name: Install project dependencies
        run: npm ci --production   ## For the app's build routine

      - id: install-action-modules
        name: Install action dependencies
        run: npm install archieml  ## For the deployment routine

      - id: get-slug
        name: Get slug
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            // import modules
            const fs = require('fs');
            const archieml = require('archieml');

            // Read in the slug file
            const meta = archieml.load(fs.readFileSync('_data/meta.aml', 'utf8'));

            // Pull the slug
            const slug = meta.slug.trim();
            console.log(`slug -> ${slug}`);

            // If we get this far, we're good to go.
            return meta.slug;

      - id: npm-build
        name: Build project distribution
        run: npm run build
        env:
          BAKER_PATH_PREFIX: ${{ steps.get-slug.outputs.result }}